### PR TITLE
Fix #2615 - allow special characters in dash-table column IDs

### LINKED ISSUE #2615: [BUG] DataTable Failed to execute 'querySelector' on 'Element' - Line break in column id
```
Error: Failed to execute 'querySelector' on 'Element': 'tr:nth-of-type(1) th[data-dash-column="ccc

ddd"]:not(.phantom-cell)' is not a valid selector.
```
This happens when the column id has a line break (e.g. `{'name':'aaabbb', 'id':'aaa\nbbb'}`) but not when the line break is in the name (e.g. `{'name':'aaa\nbbb', 'id':'aaabbb'}`).

**Traceback:**
```
Error: Failed to execute 'querySelector' on 'Element': 'tr:nth-of-type(1) th[data-dash-column="ccc

ddd"]:not(.phantom-cell)' is not a valid selector.

    at u.value (http://127.0.0.1:8050/_dash-component-suites/dash/dash_table/async-table.js:2:334450)

    at u.value (http://127.0.0.1:8050/_dash-component-suites/dash/dash_table/async-table.js:2:327840)

    at commitLifeCycles (http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_10_2m1687358438.14.0.js:19970:24)

    at commitLayoutEffects (http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_10_2m1687358438.14.0.js:22938:9)

    at HTMLUnknownElement.callCallback (http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_10_2m1687358438.14.0.js:182:16)
    at Object.invokeGuardedCallbackDev (http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_10_2m1687358438.14.0.js:231:18)
    at invokeGuardedCallback (http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_10_2m1687358438.14.0.js:286:33)
    at commitRootImpl (http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_10_2m1687358438.14.0.js:22676:11)
    at unstable_runWithPriority (http://127.0.0.1:8050/_dash-component-suites/dash/deps/react@16.v2_10_2m1687358438.14.0.js:2685:14)
    at runWithPriority$1 (http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_10_2m1687358438.14.0.js:11174:12)
```
**MRE:**
```

from dash import Dash, dash_table, html
import pandas as pd

df = pd.DataFrame({
    "aaa\nbbb":[4,5,6], 
    "ccc\nddd":[1,2,3]
})

app = Dash(__name__)

app.layout = html.Div([
    dash_table.DataTable(
       id='table',
       columns=[
           {"name": "aaabbb", "id": "aaa\nbbb"} ,
           {"name": "cccddd", "id": "ccc\nddd"} 
           ],
       data=df.to_dict('records'),
   )
])

if __name__ == '__main__':
    app.run(debug=True)
```

**Env:**
Python 3.9.0
dash==2.10.2

### PR DESCRIPTION
**Pull request by alexcjohnson**
Setting these characters in the DOM attribute is OK, but they need to be escaped in `querySelector`.

## Contributor Checklist
- [x] I have run the tests locally and they passed. (refer to testing section in [contributing](https://github.com/plotly/dash/blob/master/CONTRIBUTING.md))
- [x] I have added tests, or extended existing tests, to cover any new features or bugs fixed in this PR
- [x] I have added entry in the `CHANGELOG.md`

### CODE REVIEW

File: components/dash-table/src/dash-table/components/ControlledTable/index.tsx [hunk 1]
```diff
@@ -177,7 +177,11 @@ export default class ControlledTable extends PureComponent<ControlledTableProps>
                     active.row !== active_cell?.row)
             ) {
                 const target = this.$el.querySelector(
-                    `td[data-dash-row="${active_cell.row}"][data-dash-column="${active_cell.column_id}"]:not(.phantom-cell)`
+                    `td[data-dash-row="${
+                        active_cell.row
+                    }"][data-dash-column="${CSS.escape(
+                        active_cell.column_id
+                    )}"]:not(.phantom-cell)`
```
Comment (T4rk1n) [inline components/dash-table/src/dash-table/components/ControlledTable/index.tsx:184]: That became a bit harder to read on multiple line, I would destructure the `active_cell` and put the escaped column id in a variable.

Comment (alexcjohnson) [reply components/dash-table/src/dash-table/components/ControlledTable/index.tsx]: dunno if it's net easier to read or not, but I DRYed this in https://github.com/plotly/dash/pull/2619/commits/3391ee9910359115489b4763a59c94128a1a6089

**Review by T4rk1n — APPROVED** [review]
:woman_dancing:
