### PR TITLE
Fix pattern matching in side updates (running/progress/set_props)

### LINKED ISSUE #2863: [BUG] running does not support wildcards in ids
**Describe your context**
Please provide us your environment, so we can easily reproduce the issue.

-  replace the result of `pip list | grep dash` below
```
dash                                     2.17.0
dash-core-components                     2.0.0
dash-html-components                     2.0.0
dash-table                               5.0.0
dash-bootstrap-components                1.6.0

```

**Describe the bug**

Using wildcards in ids for Outputs in the running kwarg does leads to `itempath is undefined` error.

**Expected behavior**

Wildcards are properly resolved and matching components are updated while the callback is running.

**MVE**

```
from time import sleep

import dash_bootstrap_components as dbc
from dash import MATCH, Input, Output, callback

layout = [
    dbc.Button(
        "Test1",
        id={"component": "button", "index": "1"},
    ),
    dbc.Button(
        "Test2",
        id={"component": "button", "index": "2"},
    ),
]


@callback(
    Output({"component": "button", "index": MATCH}, "color"),
    Input({"component": "button", "index": MATCH}, "n_clicks"),
    running=[
        (Output({"component": "button", "index": MATCH}, "children"), "running", "finished"),
    ],
    prevent_initial_call=True,
)
def test(_) -> str:
    sleep(3)
    return "warning"
```

### PR DESCRIPTION
**Pull request by T4rk1n**
Fix #2863

Fixes for cases where the given id has a `MATCH`, `ALL`, `ALLSMALLER` wildcard in callback `running` argument, progress for background callbacks and `set_props`.

### CODE REVIEW

**Review by gvwilson — APPROVED** [review]
thank you

File: dash/dash-renderer/src/actions/callbacks.ts [hunk 1]
```diff
@@ -340,33 +342,108 @@ function updateComponent(component_id: any, props: any) {
     };
 }
 
-function sideUpdate(outputs: any, dispatch: any) {
-    toPairs(outputs).forEach(([id, value]) => {
-        let componentId = id,
-            propName;
+function parsePMCId(id: string) {
```
Comment (emilykl) [inline dash/dash-renderer/src/actions/callbacks.ts:345]: There's a lot of magic numbers in this function (`+2`, `+1`) -- could you add a comment explaining some of the string manipulations here?

Comment (T4rk1n) [reply dash/dash-renderer/src/actions/callbacks.ts:345]: It's just the indexes of the strings, I think it's pretty readable if you know the format:
`{"key":"value"}.propName` or just the dictionary, so index refers to position of `}`, if the `index + 2  < id.length` means there is more data after the index and `.`, the propname starts at index + 2 and componentId is 0 to index + 1.

Comment (emilykl) [reply dash/dash-renderer/src/actions/callbacks.ts:345]: got it, that makes sense, thanks! Could you add that format as a comment in the code?

Comment (alexcjohnson) [reply dash/dash-renderer/src/actions/callbacks.ts:345]: This looks duplicative of:

https://github.com/plotly/dash/blob/09252f8d2f690480cc468b2e015f9e2417dc90ad/dash/dash-renderer/src/actions/dependencies.js#L93

File: tests/integration/callbacks/test_wildcards.py [hunk 2]
```diff
@@ -552,3 +553,65 @@ def update_selected_values(values):
...
+                Output({"component": "button", "index": MATCH}, "children"),
+                "running",
+                "finished",
+            ),
+            (Output({"component": "button", "index": ALL}, "disabled"), True, False),
+        ],
+        prevent_initial_call=True,
+    )
+    def on_click(_) -> str:
+        time.sleep(1)
```
Comment (alexcjohnson) [inline tests/integration/callbacks/test_wildcards.py:593]: Can we do this with a lock instead of a delay?

File: dash/dash-renderer/src/actions/callbacks.ts (hunk 1 above)
Comment (T4rk1n) [reply dash/dash-renderer/src/actions/callbacks.ts:345]: This handle case where the prop name is not attached to the key, which comes with `set_props` so it searches for `}` instead of a dot.

**Comment by T4rk1n** [comment]
I notice the running is not available/working with clientside callbacks, it could be working with a bit of refactor and I think could be useful when the clientside callback returns a promise.

File: dash/dash-renderer/src/actions/callbacks.ts (hunk 1 above)
Comment (alexcjohnson) [reply dash/dash-renderer/src/actions/callbacks.ts:345]: OK - can we at least put these in the same location - maybe move them both to a new file so it's easier to find them and we avoid making any more of them?

My main concern with doing this in slightly different ways is accidentally introducing additional constraints on what constitutes a valid ID, and/or causing an error with certain IDs. I think your logic here is OK, as you only get to searching for `}` after you already know the ID starts with `{` which is an [invalid character](https://github.com/plotly/dash/blob/b1c6efb08d5f80e873d95f489e0c8d65335aed84/dash/_validate.py#L107) for string IDs - but that's something we need to check carefully every time we modify the ID handling code.

**Review by ndrezn — APPROVED** [review]
💃 🚀

**Comment by gvwilson** [comment]
💯

File: dash/dash-renderer/src/actions/callbacks.ts (hunk 1 above)
Comment (alexcjohnson) [reply dash/dash-renderer/src/actions/callbacks.ts]: Thanks for putting the new function in a new file. The existing function is still in its old location though, so at some point please let's bring that one into the new file too.
