### PR TITLE
Make focused dropdowns searchable without first opening

### LINKED ISSUE #3572: [BUG] Dash 4.0.0rc5 dcc.Dropdowns
Hi
We're getting feedback from our users that the new dropdowns in 4.0.0 are deprecating a really nice behavior in the old dcc.Dropdowns.

**Describe your context**
Please provide us your environment, so we can easily reproduce the issue.

-  replace the result of `pip list | grep dash` below
```
dash                                     4.0.0rc5
dash-ag-grid                             31.3.1
dash-bootstrap-components                2.0.4
dash-bootstrap-templates                 1.3.0
dash-extensions                          1.0.20rc4
```

**Describe the bug**

When "tab"'ing around. In the old dcc.Dropdown you would be directed into search if you started searching when highlighted:

It's not possible to search on highlight anymore:
Image

Another nice thing about the old search, was that it had a "top 1" select on Enter behavior due to how the focus worked. I would expect in the new, that if I am in the search and hits Enter, it would select the "top 1" element. Here Enter does nothing anymore.

Image

Going from the old flow to the new creates the user flow:

_before_
"tab" -> "write" -> "enter" (done)

_after_
"tab" -> arrow-down / enter -> "write" -> "arrow-down" -> "enter" -> "esc" (done) 

**Expected behavior**

In the old dcc.Dropdown version it was default that I could search when starting to write (when highlighted) and select the first option ("top 1" select) on Enter behavior.

Image

**Screenshots**
In another project, we have a similar dropdown as 4.0, but it behaves more like the old, as the focus is auto-shifted.

Image

### PR DESCRIPTION
**Pull request by KoolADE85**
This PR updates dropdowns to be searchable without first opening:

* When focused, you can now start typing and the dropdown will automatically open with the search field focused.
* Pressing enter while searching will select/deselect the first available option.

Fixes #3572 

## Contributor Checklist

- [x] I have run the tests locally and they passed. (refer to testing section in [contributing](https://github.com/plotly/dash/blob/master/CONTRIBUTING.md))
- [x] I have added tests, or extended existing tests, to cover any new features or bugs fixed in this PR

### optionals

- [x] I have added entry in the `CHANGELOG.md`
- [ ] If this PR needs a follow-up in **dash docs**, **community thread**, I have mentioned the relevant URLS as follows
    -  [ ] this GitHub [#PR number]() updates the dash docs
    -  [ ] here is the show and tell thread in Plotly Dash community

### CODE REVIEW

File: components/dash-core-components/src/fragments/Dropdown.tsx [hunk 1]
```diff
@@ -475,6 +495,22 @@ const Dropdown = (props: DropdownProps) => {
...
+                                    ) {
+                                        return;
+                                    }
+                                    const firstVal = displayOptions[0].value;
+                                    const isSelected =
+                                        sanitizedValues.includes(firstVal);
+                                    const newSelection = isSelected
+                                        ? without([firstVal], sanitizedValues)
+                                        : append(firstVal, sanitizedValues);
+                                    updateSelection(newSelection);
```
Comment (T4rk1n) [inline components/dash-core-components/src/fragments/Dropdown.tsx:554]: I think this would read better with a standard if else.

**Review by T4rk1n — APPROVED** [review]
💃 Looks good.
