### PR TITLE
Fix clientside pattern matching with a dot in the id.

### LINKED ISSUE #3163: Error "Unterminated string in JSON at position 11 (line 1 column 12)" from client side callback if id dict contains dot symbol
**Describe your context**
python --version
Python 3.13.1

```
dash                                     2.18.2
dash_ag_grid                             31.3.0
dash-bootstrap-components                1.7.1
dash-core-components                     2.0.0
dash-extensions                          1.0.20
dash-html-components                     2.0.0
dash-leaflet                             1.0.15
dash-resizable-panels                    0.1.0
dash_responsive_grid_layout              0.3.0
dash-table                               5.0.0
```

**Describe the bug**

If components that have a dot symbol in a id dictionary field are used in a client side callback, when the callback is called an error "Unterminated string in JSON at position 11 (line 1 column 12)" occurs and the client side function is not called.

Full stack trace:
```
SyntaxError: Unterminated string in JSON at position 11 (line 1 column 12)

    at JSON.parse (<anonymous>)

    at getTriggeredId (http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_18_2m1733903574.dev.js:977:26)

    at _callee2$ (http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_18_2m1733903574.dev.js:598:46)

    at tryCatch (http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_18_2m1733903574.dev.js:424:1062)

    at Generator.<anonymous> (http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_18_2m1733903574.dev.js:424:3006)

    at Generator.next (http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_18_2m1733903574.dev.js:424:1699)

    at asyncGeneratorStep (http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_18_2m1733903574.dev.js:430:70)

    at _next (http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_18_2m1733903574.dev.js:431:163)

    at http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_18_2m1733903574.dev.js:431:299

    at new Promise (<anonymous>)
```

**Expected behavior**

When a client side callback is triggered with components that have dot symbol in id, no error occurs and the specified client side function is called.

**Reproducible example**

```python
from dash import MATCH, Dash, Input, Output, html

if __name__ == "__main__":
    app = Dash()
    app.layout = html.Div(
        id="app-container",
        style={
            "display": "flex",
            "align-items": "center",
            "flex-direction": "column",
            "gap": "10px",
            "margin": "10px",
        },
        children=[
            html.Div(
                id={"type": "output", "index": "1.2"},
                children="Click the button",
            ),
            html.Button(
                id={"type": "input", "index": "1.2"},
                children="Submit",
            ),
        ],
    )
    app.clientside_callback(
        """
        function(n_clicks) {
            console.log("hi there", n_clicks);
            return "Hello World!"
        }
        """,
        Output({"type": "output", "index": MATCH}, "children"),
        Input({"type": "input", "index": MATCH}, "n_clicks"),
        prevent_initial_call=True,
    )

    app.run_server(debug=True)
```

### PR DESCRIPTION
**Pull request by T4rk1n**
Fixes #3163

### CODE REVIEW

File: dash/dash-renderer/src/actions/callbacks.ts [hunk 1]
```diff
@@ -661,9 +661,14 @@ function getTriggeredId(triggered: string[]): string | object | undefined {
     // for regular callbacks,  takes the first triggered prop_id, e.g.  "btn.n_clicks" and returns "btn"
     // for pattern matching callback, e.g. '{"index":0, "type":"btn"}' and returns {index:0, type: "btn"}'
     if (triggered && triggered.length) {
-        let componentId = triggered[0].split('.')[0];
-        if (componentId.startsWith('{')) {
-            componentId = JSON.parse(componentId);
+        const trig = triggered[0];
+        let componentId;
+        if (trig.startsWith('{')) {
```
Comment (gvwilson) [inline dash/dash-renderer/src/actions/callbacks.ts:666]: worth stripping whitespace from `triggered[0]` before this test?

**Review by gvwilson — APPROVED** [review]
one small suggestion but :+1: to merge

File: dash/dash-renderer/src/actions/callbacks.ts (hunk 1 above)
Comment (T4rk1n) [reply dash/dash-renderer/src/actions/callbacks.ts:666]: No, we create this composite, there is no whitespace possible.
